### ISSUE TITLE
Aya-login cannot run

### ISSUE THREAD

**Issue by xingyuanbu** [frantic1048/aya-login#1]
hi o1*5,
之前一直在用aya-login，非常的好用呢。不过最近它在我的电脑上不好使了。具体表现为：在10.0.0.55页面无法载入loli登录页面，即使刷新多次也无法载入。更新过油猴和aya-login也不能使情况好转。

环境：chrome  46.0.2490.71 m; Tampermonkey v3.11

**Comment by frantic1048** [comment]
感谢你的支持～

这个问题已经确认了，我在寻找问题原因，似乎是近来校园网又魔改了什么东西造成的。

**Comment by frantic1048** [comment]
@sefira 已经搞定了，Github Pages 那边我开了 CDN 刷新比较慢，你可以直接戳这个链接安装试试：[http://fff.ac/czooeu](http://fff.ac/czooeu)
